---
- name: Import the 1Password key
  become: true
  become_user: aur_builder
  shell: |
    cat << EOF | gpg --import
    {{ lookup('file', role_path + '/files/1password.asc') }}
    EOF
  register: import_1password_key
  changed_when: >
    "gpg:               imported: 1" in import_1password_key.stderr_lines

- name: Install `1password` AUR package
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: 1password
    state: present
