---
- name: Import the mullvad key
  become: true
  become_user: aur_builder
  shell: |
    cat << EOF | gpg --import
    {{ lookup('file', role_path + '/files/mullvad.asc') }}
    EOF
  register: import_mullvad_key
  changed_when: >
    "gpg:               imported: 1" in import_mullvad_key.stderr_lines

- name: Install `mullvad-vpn-bin` AUR package
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: mullvad-vpn-bin
    state: present
