---
- name: Install `obsidian` AppImage file
  get_url:
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_version }}/Obsidian-{{ obsidian_version }}.AppImage
    dest: $HOME/Applications/Obsidian-{{ obsidian_version }}.AppImage
    mode: u=rwx,g=rx,o=rx
